// 80 oracle answers in Gen Z dialect. Each leads with a clear verdict
// (yes / granted / approved / cleared / bet  —  no / denied / hard no /
// negative / permission revoked) so the ruling is unambiguous; the
// slang lives in the riff after the colon. Roughly 50/50 split.

export const ANSWERS: readonly string[] = [
  // ----- Yes (40) -----
  'Yes. You ate this prompt.',
  'Bet. Go off, bestie.',
  'Yes. The bowl said periodt.',
  'Granted. Your aura is bussin today.',
  'Yes. You understood the assignment.',
  'Approved. Slay responsibly.',
  'Yes. The plumbing is lowkey rooting for you.',
  'Cleared. Main character energy detected.',
  'Yes. The toilet said no cap — go.',
  'Granted. +1000 aura points.',
  "Yes. It's giving hall pass.",
  'Bet. The bowl approves of your rizz.',
  'Yes. Lock in and go.',
  "Approved. Don't be sus about it.",
  'Yes. The flush is your hype man.',
  "Granted. You're in your hallway era.",
  'Yes fr fr. Walk it out.',
  'Approved. The toilet caught your vibes in 4K.',
  'Yes. The drain stans you.',
  'Cleared. Touch grass on the way back.',
  "Yes. The bowl is giving green flag.",
  'Permission granted. Go be demure.',
  "Yes. The pipes said 'real.'",
  'Granted. Make it a canon event.',
  'Yes. Ate. Left no crumbs. Go.',
  'Bet. Energy is immaculate.',
  'Yes. Mother is mothering.',
  'Granted. The bowl said say less.',
  'Yes. Vibe check: passed.',
  'Approved. Glow up out there.',
  'Yes. Manifested. Confirmed.',
  'Bet. You cooked. Go.',
  'Yes. The drain is in its supportive era.',
  'Granted. Caught in 4K being valid.',
  'Yes. Gatekeep nothing. Go.',
  'Approved. The toilet stans your strut.',
  'Yes. Pass acquired. No notes.',
  'Bet. The pipes are quietly gagged.',
  "Yes. You're so for real.",
  'Granted. Locked in. Cleared.',

  // ----- No (40) -----
  "No. That's giving NPC behavior.",
  'Hard no. -500 aura points.',
  'Denied. The flush is so over you.',
  'No. The bowl said cap.',
  "Negative. You're lowkey crashing out.",
  'No. The toilet is not the vibe today.',
  'Hard no. Sit down. Be humble.',
  'Denied. The pipes are chronically over it.',
  'No. The drain caught the ick.',
  'Permission revoked. That was sus.',
  'No. The bowl said bffr.',
  "Hard no. The flush ratio'd you.",
  'Denied. Bestie. No.',
  "No. You're yapping. Sit down.",
  'Negative. The toilet does not stan.',
  "No. The graffiti L'd you.",
  'Denied. That request was so mid.',
  'No. The hand dryer side-eyed you.',
  'Hard no. The plumbing has receipts.',
  'No. Read the room. The bowl said L.',
  'Denied. Your rizz is not rizzing.',
  'No. Lock in at your desk.',
  'Negative. The toilet is not delulu.',
  'No. Touch grass. Mentally. From your seat.',
  'Denied. Skibidi. No.',
  'No. That ask was so cheugy.',
  'Hard no. Caught in 4K being annoying.',
  'Denied. Big mid energy.',
  'No. Vibes are off.',
  'Negative. The audacity.',
  'No. The toilet wants you to bffr.',
  "Hard no. We don't do that here.",
  'Denied. The water is not entertaining this.',
  'No. Brain rot detected.',
  'Permission revoked. Cringe.',
  "No. The bowl ratio'd your essence.",
  'Hard no. Stop yapping.',
  'Denied. -2000 aura. Sit.',
  "No. That's so npc-coded.",
  'Negative. The toilet has standards.',
] as const;

export function getRandomAnswer(): string {
  return ANSWERS[Math.floor(Math.random() * ANSWERS.length)];
}
